import canonicalLaneMathlib.AdmissibleClass
import ConvergenceAbsoluteConvergenceFourierTrigonometricFoundationCanonicalLaneLean.ConvergenceTesting
import ConvergenceAbsoluteConvergenceFourierTrigonometricFoundationCanonicalLaneLean.AbsoluteConvergence
import ConvergenceAbsoluteConvergenceFourierTrigonometricFoundationCanonicalLaneLean.FourierSeries

namespace HautevilleHouse
namespace ConvergenceAbsoluteConvergenceFourierTrigonometricFoundationCanonicalLaneLean

def ConstrainedConvergenceClosure (A : AdmissibleClass) : Prop :=
  bridgeClosed A ∧ gateClosed A

theorem constrained_convergence_endgame (A : AdmissibleClass) :
    ConstrainedConvergenceClosure A := by
  exact And.intro (bridge_from_admissible_class A) (gate_from_admissible_class A)

end ConvergenceAbsoluteConvergenceFourierTrigonometricFoundationCanonicalLaneLean
end HautevilleHouse